# Generated by Django 2.1.3 on 2018-12-06 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('en_portada', models.BooleanField(default=False)),
                ('categoria', models.CharField(max_length=100)),
                ('imagen_destacada_uno', models.FileField(upload_to='articulos/uno/')),
                ('redactado_por', models.CharField(blank=True, default='Equipo MX', max_length=300, null=True)),
                ('status', models.CharField(choices=[('Publicado', 'Publicado'), ('No Publicado', 'No publicado')], default='Publicado', max_length=50)),
                ('cuerpo_uno', models.TextField()),
                ('imagen_destacada_dos', models.FileField(blank=True, null=True, upload_to='articulos/dos/')),
                ('cuerpo_dos', models.TextField(blank=True, null=True)),
                ('video_tipo', models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo'), ('sin video', 'sin video')], default='sin video', max_length=50)),
                ('urlvideo', models.URLField(blank=True, null=True)),
                ('llamada_accion_uno', models.CharField(choices=[('Contactar', 'Contactar'), ('Visitar', 'Visitar'), ('Compar', 'Comprar'), ('Llamar', 'Llamar'), ('Sinllamada', 'Sinllamada')], max_length=50)),
                ('imagen_llamada_uno', models.FileField(blank=True, null=True, upload_to='llamadas')),
                ('url_llamada_uno', models.TextField(blank=True, null=True)),
                ('llamada_accion_dos', models.CharField(choices=[('Contactar', 'Contactar'), ('Visitar', 'Visitar'), ('Compar', 'Comprar'), ('Llamar', 'Llamar'), ('Sinllamada', 'Sinllamada')], max_length=50)),
                ('imagen_llamada_dos', models.FileField(blank=True, null=True, upload_to='llamadas')),
                ('url_llamada_dos', models.TextField(blank=True, null=True)),
                ('cortesia_de', models.CharField(blank=True, max_length=300, null=True)),
                ('link_cortesia', models.URLField(blank=True, null=True)),
                ('fecha_mostrada', models.DateField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('origen_revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.Revista')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_asignado', to='cliente.Cliente')),
                ('usuario_publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
