# Generated by Django 2.1.3 on 2018-12-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patrocinador', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('razonsocial', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('numero_cuenta', models.IntegerField(blank=True, null=True)),
                ('iniciocontrato', models.DateField()),
                ('terminocontrato', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('plan_contratado', models.CharField(max_length=50)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos')),
                ('revista_pertenencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_origen', to='revista.Revista')),
            ],
        ),
        migrations.CreateModel(
            name='Planesvigentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_procedencia', to='revista.Revista')),
            ],
        ),
    ]
